# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schema_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('dbhost', models.CharField(max_length=40, verbose_name='主机地址')),
                ('dbport', models.IntegerField(verbose_name='端口')),
                ('dbrule', models.CharField(max_length=50, verbose_name='角色')),
                ('cluster_user', models.CharField(max_length=50, verbose_name='用户名')),
                ('cluster_passwd', models.CharField(max_length=300, verbose_name='密码')),
                ('cluster_service', models.CharField(max_length=50, verbose_name='所属业务线')),
                ('cluster_development', models.CharField(max_length=50, verbose_name='开发')),
                ('environment', models.IntegerField(verbose_name='环境')),
                ('remarks', models.CharField(max_length=50, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='service_line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='集群名称')),
            ],
        ),
    ]
